// Generates src/version.ts from package.json so the version is bundled
// without importing JSON at runtime. Mirrors microsoft/azure-devops-mcp.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const out = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.\nexport const packageVersion = ${JSON.stringify(
  pkg.version,
)};\n`;
writeFileSync(join(root, "src", "version.ts"), out);
process.stderr.write(`Generated src/version.ts (v${pkg.version})\n`);
